all: compile execute

compile:
	c++ -o tridiag.exe tridiag.cpp

execute:
	./tridiag.exe 10 special
	./tridiag.exe 10 general
	./tridiag.exe 100 special
	./tridiag.exe 100 general
	./tridiag.exe 1000 special
	./tridiag.exe 1000 general
