all: compile execute

compile:
	c++ -o poisson.exe poisson.cpp

execute:
	./poisson.exe 10 special
	./poisson.exe 10 general
	./poisson.exe 100 special
	./poisson.exe 100 general
	./poisson.exe 1000 special
	./poisson.exe 1000 general
